steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg REACT_APP_FIREBASE_API_KEY="$$REACT_APP_FIREBASE_API_KEY" \
          --build-arg REACT_APP_FIREBASE_AUTH_DOMAIN="$$REACT_APP_FIREBASE_AUTH_DOMAIN" \
          --build-arg REACT_APP_FIREBASE_PROJECT_ID="$$REACT_APP_FIREBASE_PROJECT_ID" \
          --build-arg REACT_APP_FIREBASE_STORAGE_BUCKET="$$REACT_APP_FIREBASE_STORAGE_BUCKET" \
          --build-arg REACT_APP_FIREBASE_MESSAGING_SENDER_ID="$$REACT_APP_FIREBASE_MESSAGING_SENDER_ID" \
          --build-arg REACT_APP_FIREBASE_APP_ID="$$REACT_APP_FIREBASE_APP_ID" \
          --build-arg REACT_APP_FIREBASE_MEASUREMENT_ID="$$REACT_APP_FIREBASE_MEASUREMENT_ID" \
          -t "gcr.io/pokemon-statistics/pokemon-app:$COMMIT_SHA" .
    env:
      - 'REACT_APP_FIREBASE_API_KEY'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN'
      - 'REACT_APP_FIREBASE_PROJECT_ID'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID'
      - 'REACT_APP_FIREBASE_APP_ID'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/pokemon-statistics/pokemon-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'pokemon-app', '--image', 'gcr.io/pokemon-statistics/pokemon-app:$COMMIT_SHA', '--region', 'us-central1']

availableSecrets:
  secretManager:
    - versionName: projects/pokemon-statistics/secrets/FIREBASE_API_KEY/versions/latest
      env: REACT_APP_FIREBASE_API_KEY
    - versionName: projects/pokemon-statistics/secrets/FIREBASE_AUTH_DOMAIN/versions/latest
      env: REACT_APP_FIREBASE_AUTH_DOMAIN
    - versionName: projects/pokemon-statistics/secrets/FIREBASE_PROJECT_ID/versions/latest
      env: REACT_APP_FIREBASE_PROJECT_ID
    - versionName: projects/pokemon-statistics/secrets/FIREBASE_STORAGE_BUCKET/versions/latest
      env: REACT_APP_FIREBASE_STORAGE_BUCKET
    - versionName: projects/pokemon-statistics/secrets/FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
    - versionName: projects/pokemon-statistics/secrets/FIREBASE_APP_ID/versions/latest
      env: REACT_APP_FIREBASE_APP_ID
    - versionName: projects/pokemon-statistics/secrets/FIREBASE_MEASUREMENT_ID/versions/latest
      env: REACT_APP_FIREBASE_MEASUREMENT_ID

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'pokemon-statistics@pokemon-statistics.iam.gserviceaccount.com'